#!/bin/sh
#
# fluxbox startup-script:
# Lines starting with a '#' are ignored.

polybar catppuccin &

# Change your keymap:
xmodmap "/home/spulick/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# Adding in a resoliton fixing thing
xrandr --output eDP-1 --mode 1920x1080 &

# adding a wallpaper
feh --bg-scale ~/.fluxbox/wallpaper/nasa-bXrBoMT1NCo-unsplash.jpg &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/spulick/.fluxbox/log"
